### ISSUE TITLE
Error when executing a cypher query

### ISSUE THREAD

**Issue by wallerprogramm** [opencypher/morpheus#889]
I do always get a `java.lang.ArrayIndexOutOfBoundsException: 10582` whenever I run a cypher query with CAPS.
I use spark-cypher 0.3.1 and spark-sql_2.12 2.4.0
To make that reproducible I created a reduced version of the Recommendation.scala example:
```
package org.opencypher.spark.examples

import org.opencypher.okapi.api.graph.Namespace
import org.opencypher.okapi.neo4j.io.MetaLabelSupport._
import org.opencypher.okapi.neo4j.io.testing.Neo4jTestUtils._
import org.opencypher.spark.api.{CAPSSession, GraphSources}
import org.opencypher.spark.util.App

/**
  * This application demonstrates the integration of three data sources into a single graph which is used for computing
  * recommendations. Two graphs are loaded from separate Neo4j databases, one graph is loaded from csv files stored in
  * the local file system.
  */
object RecommendationExample extends App {

  // Create CAPS session
  implicit val caps: CAPSSession = CAPSSession.local()

  // Connect to two Neo4j instances and populate them with social network data
  // To run two test instances you may use
  //  ./gradlew :okapi-neo4j-io-testing:neo4jStartTwoInstances
  //  ./gradlew :okapi-neo4j-io-testing:neo4jStopTwoInstances
  val neo4jServerUS = connectNeo4j(socialNetworkUS, "bolt://localhost:7687")

  // Register Property Graph Data Sources (PGDS)

  // The graph within Neo4j is partitioned into regions using a property key. Within the data source, we map each
  // partition to a separate graph name (i.e. US and EU)
  caps.registerSource(Namespace("usSocialNetwork"), GraphSources.cypher.neo4j(neo4jServerUS.config))

  // File-based CSV GDS
  caps.registerSource(Namespace("purchases"), GraphSources.fs(rootPath = s"${getClass.getResource("/fs-graphsource/caps").getFile}").csv)

  // Print all available graphs
  println("*** Graph names in catalog ***")
  println(caps.catalog.graphNames.mkString(System.lineSeparator()))

  // Start analytical workload

  /**
    * Returns a query that creates a graph containing persons that live in the same city and
    * know each other via 1 to 2 hops. The created graph contains a CLOSE_TO relationship between
    * each such pair of persons and is stored in the session catalog using the given graph name.
    */
  def cityFriendsQuery(fromGraph: String): String =
    s"""FROM GRAPH $fromGraph
       |MATCH (a:Person)-[:LIVES_IN]->(city:City)<-[:LIVES_IN]-(b:Person),
       |      (a)-[:KNOWS*1..2]->(b)
       |CONSTRUCT
       |  ON $fromGraph
       |  CREATE (a)-[:CLOSE_TO]->(b)
       |RETURN GRAPH
      """.stripMargin

  // Find persons that are close to each other in the US social network
  val usFriends = caps.cypher(cityFriendsQuery(s"usSocialNetwork.$entireGraphName")).graph

  // Union the US and EU graphs into a single graph 'allFriends' and store it in the session
  caps.catalog.store("allFriends", usFriends)

  // Print all available graphs
  println("*** Graph names in catalog ***")
  println(caps.catalog.graphNames.mkString(System.lineSeparator()))

  // Connect the social network with the products network using equal person and customer emails
  val connectedCustomers = caps.cypher(
    s"""FROM GRAPH allFriends
       |MATCH (p:Person)
       |FROM GRAPH purchases.products
       |MATCH (c:Customer)
       |WHERE c.name = p.name
       |CONSTRUCT ON purchases.products, allFriends
       |  CREATE (c)-[:IS]->(p)
       |RETURN GRAPH
      """.stripMargin).graph

  // Compute recommendations for 'target' based on their interests and what persons close to the
  // 'target' have already bought and given a helpful and positive rating
  val recommendationTable = connectedCustomers.cypher(
    s"""|MATCH (target:Person)<-[:CLOSE_TO]-(person:Person),
        |      (target)-[:HAS_INTEREST]->(i:Interest),
        |      (person)<-[:IS]-(x:Customer)-[b:BOUGHT]->(product:Product {category: i.name})
        |WHERE b.rating >= 4 AND (b.helpful * 1.0) / b.votes > 0.6
        |WITH * ORDER BY product.rank
        |RETURN DISTINCT product.title AS product, target.name AS name
        |LIMIT 3
      """.stripMargin).records

  // Print the results
  recommendationTable.show

  // Shutdown Neo4j test instance
  neo4jServerUS.close()

  def socialNetworkUS =
    """
       CREATE (nyc:City {name: "New York City"})
       CREATE (sfo:City {name: "San Francisco"})
       CREATE (alice:Person   {name: "Alice"}  )-[:LIVES_IN]->(nyc)
       CREATE (bob:Person     {name: "Bob"}    )-[:LIVES_IN]->(nyc)
       CREATE (eve:Person     {name: "Eve"}    )-[:LIVES_IN]->(nyc)
       CREATE (carol:Person   {name: "Carol"}  )-[:LIVES_IN]->(sfo)
       CREATE (carl:Person    {name: "Carl"}   )-[:LIVES_IN]->(sfo)
       CREATE (dave:Person    {name: "Dave"}   )-[:LIVES_IN]->(sfo)
       CREATE (eve)<-[:KNOWS]-(alice)-[:KNOWS]->(bob)-[:KNOWS]->(eve)
       CREATE (carol)-[:KNOWS]->(carl)-[:KNOWS]->(dave)
       CREATE (book_US:Interest {name: "Book"})
       CREATE (dvd_US:Interest {name: "DVD"})
       CREATE (video_US:Interest {name: "Video"})
       CREATE (music_US:Interest {name: "Music"})
       CREATE (bob)-[:HAS_INTEREST]->(book_US)
       CREATE (eve)-[:HAS_INTEREST]->(dvd_US)
       CREATE (carl)-[:HAS_INTEREST]->(video_US)
       CREATE (dave)-[:HAS_INTEREST]->(music_US)
    """

}
// end::full-example[]
```
While running the first cypher query I get java.lang.ArrayIndexOutOfBoundsException: 10582
Here is my console output:
```
Using Spark's default log4j profile: org/apache/spark/log4j-defaults.properties
19/04/12 19:17:16 WARN Utils: Your hostname, csg-ThinkPad-T430 resolves to a loopback address: 127.0.1.1; using 192.168.1.102 instead (on interface enp0s25)
19/04/12 19:17:16 WARN Utils: Set SPARK_LOCAL_IP if you need to bind to another address
19/04/12 19:17:16 INFO SparkContext: Running Spark version 2.4.0
19/04/12 19:17:17 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
19/04/12 19:17:17 INFO SparkContext: Submitted application: caps-local-13000b2a-01bd-4598-b51d-15e918f917bf
19/04/12 19:17:17 INFO SecurityManager: Changing view acls to: csg
19/04/12 19:17:17 INFO SecurityManager: Changing modify acls to: csg
19/04/12 19:17:17 INFO SecurityManager: Changing view acls groups to: 
19/04/12 19:17:17 INFO SecurityManager: Changing modify acls groups to: 
19/04/12 19:17:17 INFO SecurityManager: SecurityManager: authentication disabled; ui acls disabled; users  with view permissions: Set(csg); groups with view permissions: Set(); users  with modify permissions: Set(csg); groups with modify permissions: Set()
19/04/12 19:17:17 INFO Utils: Successfully started service 'sparkDriver' on port 41987.
19/04/12 19:17:17 INFO SparkEnv: Registering MapOutputTracker
19/04/12 19:17:18 INFO SparkEnv: Registering BlockManagerMaster
19/04/12 19:17:18 INFO BlockManagerMasterEndpoint: Using org.apache.spark.storage.DefaultTopologyMapper for getting topology information
19/04/12 19:17:18 INFO BlockManagerMasterEndpoint: BlockManagerMasterEndpoint up
19/04/12 19:17:18 INFO DiskBlockManager: Created local directory at /tmp/blockmgr-fac7ad79-a953-42e3-bf94-ff3b4b6aa516
19/04/12 19:17:18 INFO MemoryStore: MemoryStore started with capacity 1922.4 MB
19/04/12 19:17:18 INFO SparkEnv: Registering OutputCommitCoordinator
19/04/12 19:17:18 WARN Utils: Service 'SparkUI' could not bind on port 4040. Attempting port 4041.
19/04/12 19:17:18 INFO Utils: Successfully started service 'SparkUI' on port 4041.
19/04/12 19:17:18 INFO SparkUI: Bound SparkUI to 0.0.0.0, and started at http://192.168.1.102:4041
19/04/12 19:17:18 INFO Executor: Starting executor ID driver on host localhost
19/04/12 19:17:18 INFO Utils: Successfully started service 'org.apache.spark.network.netty.NettyBlockTransferService' on port 34239.
19/04/12 19:17:18 INFO NettyBlockTransferService: Server created on 192.168.1.102:34239
19/04/12 19:17:18 INFO BlockManager: Using org.apache.spark.storage.RandomBlockReplicationPolicy for block replication policy
19/04/12 19:17:18 INFO BlockManagerMaster: Registering BlockManager BlockManagerId(driver, 192.168.1.102, 34239, None)
19/04/12 19:17:18 INFO BlockManagerMasterEndpoint: Registering block manager 192.168.1.102:34239 with 1922.4 MB RAM, BlockManagerId(driver, 192.168.1.102, 34239, None)
19/04/12 19:17:18 INFO BlockManagerMaster: Registered BlockManager BlockManagerId(driver, 192.168.1.102, 34239, None)
19/04/12 19:17:18 INFO BlockManager: Initialized BlockManager: BlockManagerId(driver, 192.168.1.102, 34239, None)
*** Graph names in catalog ***
session.emptyGraph
usSocialNetwork.graph
purchases.products
Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: 10582
	at com.thoughtworks.paranamer.BytecodeReadingParanamer$ClassReader.accept(BytecodeReadingParanamer.java:563)
	at com.thoughtworks.paranamer.BytecodeReadingParanamer$ClassReader.access$200(BytecodeReadingParanamer.java:338)
	at com.thoughtworks.paranamer.BytecodeReadingParanamer.lookupParameterNames(BytecodeReadingParanamer.java:103)
	at com.thoughtworks.paranamer.CachingParanamer.lookupParameterNames(CachingParanamer.java:90)
	at com.fasterxml.jackson.module.scala.introspect.BeanIntrospector$.getCtorParams(BeanIntrospector.scala:44)
	at com.fasterxml.jackson.module.scala.introspect.BeanIntrospector$.$anonfun$apply$1(BeanIntrospector.scala:58)
	at com.fasterxml.jackson.module.scala.introspect.BeanIntrospector$.$anonfun$apply$1$adapted(BeanIntrospector.scala:58)
	at scala.collection.TraversableLike.$anonfun$flatMap$1(TraversableLike.scala:241)
	at scala.collection.Iterator.foreach(Iterator.scala:944)
	at scala.collection.Iterator.foreach$(Iterator.scala:944)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1432)
	at scala.collection.IterableLike.foreach(IterableLike.scala:71)
	at scala.collection.IterableLike.foreach$(IterableLike.scala:70)
	at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
	at scala.collection.TraversableLike.flatMap(TraversableLike.scala:241)
	at scala.collection.TraversableLike.flatMap$(TraversableLike.scala:238)
	at scala.collection.AbstractTraversable.flatMap(Traversable.scala:104)
	at com.fasterxml.jackson.module.scala.introspect.BeanIntrospector$.findConstructorParam$1(BeanIntrospector.scala:58)
	at com.fasterxml.jackson.module.scala.introspect.BeanIntrospector$.$anonfun$apply$19(BeanIntrospector.scala:176)
	at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:234)
	at scala.collection.IndexedSeqOptimized.foreach(IndexedSeqOptimized.scala:32)
	at scala.collection.IndexedSeqOptimized.foreach$(IndexedSeqOptimized.scala:29)
	at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:194)
	at scala.collection.TraversableLike.map(TraversableLike.scala:234)
	at scala.collection.TraversableLike.map$(TraversableLike.scala:227)
	at scala.collection.mutable.ArrayOps$ofRef.map(ArrayOps.scala:194)
	at com.fasterxml.jackson.module.scala.introspect.BeanIntrospector$.$anonfun$apply$14(BeanIntrospector.scala:170)
	at com.fasterxml.jackson.module.scala.introspect.BeanIntrospector$.$anonfun$apply$14$adapted(BeanIntrospector.scala:169)
	at scala.collection.TraversableLike.$anonfun$flatMap$1(TraversableLike.scala:241)
	at scala.collection.immutable.List.foreach(List.scala:389)
	at scala.collection.TraversableLike.flatMap(TraversableLike.scala:241)
	at scala.collection.TraversableLike.flatMap$(TraversableLike.scala:238)
	at scala.collection.immutable.List.flatMap(List.scala:352)
	at com.fasterxml.jackson.module.scala.introspect.BeanIntrospector$.apply(BeanIntrospector.scala:169)
	at com.fasterxml.jackson.module.scala.introspect.ScalaAnnotationIntrospector$._descriptorFor(ScalaAnnotationIntrospectorModule.scala:22)
	at com.fasterxml.jackson.module.scala.introspect.ScalaAnnotationIntrospector$.fieldName(ScalaAnnotationIntrospectorModule.scala:30)
	at com.fasterxml.jackson.module.scala.introspect.ScalaAnnotationIntrospector$.findImplicitPropertyName(ScalaAnnotationIntrospectorModule.scala:78)
	at com.fasterxml.jackson.databind.introspect.AnnotationIntrospectorPair.findImplicitPropertyName(AnnotationIntrospectorPair.java:467)
	at com.fasterxml.jackson.databind.introspect.POJOPropertiesCollector._addFields(POJOPropertiesCollector.java:351)
	at com.fasterxml.jackson.databind.introspect.POJOPropertiesCollector.collectAll(POJOPropertiesCollector.java:283)
	at com.fasterxml.jackson.databind.introspect.POJOPropertiesCollector.getJsonValueMethod(POJOPropertiesCollector.java:169)
	at com.fasterxml.jackson.databind.introspect.BasicBeanDescription.findJsonValueMethod(BasicBeanDescription.java:223)
	at com.fasterxml.jackson.databind.ser.BasicSerializerFactory.findSerializerByAnnotations(BasicSerializerFactory.java:348)
	at com.fasterxml.jackson.databind.ser.BeanSerializerFactory._createSerializer2(BeanSerializerFactory.java:210)
	at com.fasterxml.jackson.databind.ser.BeanSerializerFactory.createSerializer(BeanSerializerFactory.java:153)
	at com.fasterxml.jackson.databind.SerializerProvider._createUntypedSerializer(SerializerProvider.java:1203)
	at com.fasterxml.jackson.databind.SerializerProvider._createAndCacheUntypedSerializer(SerializerProvider.java:1157)
	at com.fasterxml.jackson.databind.SerializerProvider.findValueSerializer(SerializerProvider.java:481)
	at com.fasterxml.jackson.databind.SerializerProvider.findTypedValueSerializer(SerializerProvider.java:679)
	at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider.serializeValue(DefaultSerializerProvider.java:107)
	at com.fasterxml.jackson.databind.ObjectMapper._configAndWriteValue(ObjectMapper.java:3559)
	at com.fasterxml.jackson.databind.ObjectMapper.writeValueAsString(ObjectMapper.java:2927)
	at org.apache.spark.rdd.RDDOperationScope.toJson(RDDOperationScope.scala:52)
	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:145)
	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:112)
	at org.apache.spark.rdd.RDD.withScope(RDD.scala:363)
	at org.apache.spark.rdd.RDD.map(RDD.scala:370)
	at org.apache.spark.sql.SparkSession.createDataFrame(SparkSession.scala:593)
	at org.apache.spark.sql.SparkSession.createDataFrame(SparkSession.scala:352)
	at org.opencypher.spark.api.io.neo4j.Neo4jPropertyGraphDataSource.readNodeTable(Neo4jPropertyGraphDataSource.scala:121)
	at org.opencypher.spark.api.io.AbstractPropertyGraphDataSource.$anonfun$graph$1(AbstractPropertyGraphDataSource.scala:120)
	at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:234)
	at scala.collection.immutable.Set$Set3.foreach(Set.scala:167)
	at scala.collection.TraversableLike.map(TraversableLike.scala:234)
	at scala.collection.TraversableLike.map$(TraversableLike.scala:227)
	at scala.collection.AbstractSet.scala$collection$SetLike$$super$map(Set.scala:47)
	at scala.collection.SetLike.map(SetLike.scala:101)
	at scala.collection.SetLike.map$(SetLike.scala:101)
	at scala.collection.AbstractSet.map(Set.scala:47)
	at org.opencypher.spark.api.io.AbstractPropertyGraphDataSource.graph(AbstractPropertyGraphDataSource.scala:119)
	at org.opencypher.okapi.ir.impl.QueryLocalCatalog.graph(QueryLocalCatalog.scala:57)
	at org.opencypher.okapi.relational.api.graph.RelationalCypherSession.queryLocalGraphAt$1(RelationalCypherSession.scala:247)
	at org.opencypher.okapi.relational.api.graph.RelationalCypherSession.$anonfun$planRelational$1(RelationalCypherSession.scala:249)
	at org.opencypher.okapi.relational.api.planning.RelationalRuntimeContext.resolveGraph(RelationalRuntimeContext.scala:57)
	at org.opencypher.okapi.relational.impl.planning.RelationalPlanner$.planScan(RelationalPlanner.scala:272)
	at org.opencypher.okapi.relational.impl.planning.RelationalPlanner$.process(RelationalPlanner.scala:192)
	at org.opencypher.okapi.relational.impl.planning.RelationalPlanner$.process(RelationalPlanner.scala:112)
	at org.opencypher.okapi.relational.impl.planning.RelationalPlanner$.process(RelationalPlanner.scala:92)
	at org.opencypher.okapi.relational.impl.planning.RelationalPlanner$.process(RelationalPlanner.scala:253)
	at org.opencypher.okapi.relational.api.graph.RelationalCypherSession.$anonfun$planRelational$2(RelationalCypherSession.scala:251)
	at org.opencypher.okapi.relational.api.graph.RelationalCypherSession.time(RelationalCypherSession.scala:114)
	at org.opencypher.okapi.relational.api.graph.RelationalCypherSession.planRelational(RelationalCypherSession.scala:251)
	at org.opencypher.okapi.relational.api.graph.RelationalCypherSession.planCypherQuery(RelationalCypherSession.scala:210)
	at org.opencypher.okapi.relational.api.graph.RelationalCypherSession.processIR$1(RelationalCypherSession.scala:177)
	at org.opencypher.okapi.relational.api.graph.RelationalCypherSession.cypherOnGraph(RelationalCypherSession.scala:198)
	at org.opencypher.okapi.relational.api.graph.RelationalCypherSession.cypher(RelationalCypherSession.scala:128)
	at org.opencypher.spark.examples.RecommendationExample$.delayedEndpoint$org$opencypher$spark$examples$RecommendationExample$1(RecommendationExample.scala:85)
	at org.opencypher.spark.examples.RecommendationExample$delayedInit$body.apply(RecommendationExample.scala:41)
	at scala.Function0.apply$mcV$sp(Function0.scala:34)
	at scala.Function0.apply$mcV$sp$(Function0.scala:34)
	at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:12)
	at scala.App.$anonfun$main$1$adapted(App.scala:76)
	at scala.collection.immutable.List.foreach(List.scala:389)
	at scala.App.main(App.scala:76)
	at scala.App.main$(App.scala:74)
	at org.opencypher.spark.util.App.main(App.scala:34)
	at org.opencypher.spark.examples.RecommendationExample.main(RecommendationExample.scala)
```
The nodes and relationships from the `socialNetworkUS` are added in Neo4j.

**Comment by Mats-SX** [comment]
Hello @wallerprogramm and thanks for reporting this issue!

We have successfully been able to reproduce the error and we're looking into what the cause is. Interestingly enough, we were able to successfully run the whole job when we tried exactly this program _within_ CAPS' source tree (on current `master`). That gives a clue that it could be some sort of packaging problem, rather than a code bug, but investigation is still pending.

We'll reach back when we know more.
