### ISSUE TITLE
Issue with open cypher on DataFrameInputExample

### ISSUE THREAD

**Issue by purush-git** [opencypher/morpheus#946]
Hello, 
I am trying to explore on DataFrameInputExample using "org.opencypher.morpheus.examples.DataFrameInputExample" and I am running into an issue at below step. I was using "morpheus-spark-cypher" jar file extract in my spark session

```
val result = graph.cypher("MATCH (n:Person) RETURN n.name")
```

Appreciate if i can get some help to resolve this and move forward. Error message is below.

Error Message: 

```
scala>   val result = graph.cypher("MATCH (n:Person) RETURN n.name")
scala.ScalaReflectionException: object org.opencypher.morpheus.impl.table.SparkTable not found.
  at scala.reflect.internal.Mirrors$RootsBase.staticModule(Mirrors.scala:190)
  at scala.reflect.internal.Mirrors$RootsBase.staticModule(Mirrors.scala:29)
  at org.opencypher.morpheus.api.MorpheusSession$$typecreator1$1.apply(MorpheusSession.scala:55)
  at scala.reflect.api.TypeTags$WeakTypeTagImpl.tpe$lzycompute(TypeTags.scala:237)
  at scala.reflect.api.TypeTags$WeakTypeTagImpl.tpe(TypeTags.scala:237)
  at org.opencypher.okapi.relational.impl.operators.RelationalOperator$$typecreator1$1.apply(RelationalOperator.scala:48)
  at scala.reflect.api.TypeTags$WeakTypeTagImpl.tpe$lzycompute(TypeTags.scala:237)
  at scala.reflect.api.TypeTags$WeakTypeTagImpl.tpe(TypeTags.scala:237)
  at org.opencypher.okapi.trees.AbstractTreeNode.ct(AbstractTreeNode.scala:60)
  at org.opencypher.okapi.trees.AbstractTreeNode.<init>(AbstractTreeNode.scala:69)
  at org.opencypher.okapi.relational.impl.operators.RelationalOperator.<init>(RelationalOperator.scala:48)
  at org.opencypher.okapi.relational.impl.operators.Start.<init>(RelationalOperator.scala:162)
  at org.opencypher.okapi.relational.impl.planning.RelationalPlanner$.process(RelationalPlanner.scala:88)
  at org.opencypher.okapi.relational.impl.planning.RelationalPlanner$.process(RelationalPlanner.scala:105)
  at org.opencypher.okapi.relational.impl.planning.RelationalPlanner$.process(RelationalPlanner.scala:75)
  at org.opencypher.okapi.relational.impl.planning.RelationalPlanner$.process(RelationalPlanner.scala:66)
  at org.opencypher.okapi.relational.api.graph.RelationalCypherSession.$anonfun$planRelational$2(RelationalCypherSession.scala:251)
  at org.opencypher.okapi.relational.api.graph.RelationalCypherSession.time(RelationalCypherSession.scala:114)
  at org.opencypher.okapi.relational.api.graph.RelationalCypherSession.planRelational(RelationalCypherSession.scala:251)
  at org.opencypher.okapi.relational.api.graph.RelationalCypherSession.planCypherQuery(RelationalCypherSession.scala:210)
  at org.opencypher.okapi.relational.api.graph.RelationalCypherSession.processIR$1(RelationalCypherSession.scala:177)
  at org.opencypher.okapi.relational.api.graph.RelationalCypherSession.cypherOnGraph(RelationalCypherSession.scala:198)
  at org.opencypher.okapi.relational.api.graph.RelationalCypherGraph.cypher(RelationalCypherGraph.scala:106)
  at org.opencypher.okapi.relational.api.graph.RelationalCypherGraph.cypher$(RelationalCypherGraph.scala:101)
  at org.opencypher.okapi.relational.impl.graph.ScanGraph.cypher(ScanGraph.scala:43)
  ... 91 elided
```

**Comment by Mats-SX** [comment]
Hello @purush-git 

Did you use the `all` JAR when you installed Morpheus into Spark? The error seems to indicate that a class is missing, which usually is because only the immediate module with the application code was installed.

**Comment by purush-git** [comment]
Hi @Mats-SX 
Thanks for the response. I did tried with all JAR as well and ended up with the same Error. Looks like some issue in creating Relationship table while preparing for graph DB.

Few more Debugging results on this:

scala> print(personTable)
MorpheusElementTable(ElementMapping(NodePattern(NODE(:Person)),Map(PatternElement(node,NODE(:Person)) -> Map(name -> name, age -> age)),Map(PatternElement(node,NODE(:Person)) -> Map(SourceIdKey -> id))),org.opencypher.morpheus.impl.table.SparkTable$DataFrameTable@57bb97ff)

scala> print(friendsTable)
MorpheusElementTable(ElementMapping(RelationshipPattern(RELATIONSHIP(:KNOWS)),Map(PatternElement(rel,RELATIONSHIP(:KNOWS)) -> Map(since -> since)),Map(PatternElement(rel,RELATIONSHIP(:KNOWS)) -> Map(SourceIdKey -> id, SourceStartNodeKey -> source, SourceEndNodeKey -> target))),org.opencypher.morpheus.impl.table.SparkTable$DataFrameTable@7003891)

scala> personTable.collect.foreach(println)
Map(node -> MorpheusNode(id=0x00, labels=Set(), properties=Map(name -> Alice, age -> 42)))
Map(node -> MorpheusNode(id=0x01, labels=Set(), properties=Map(name -> Bob, age -> 23)))
Map(node -> MorpheusNode(id=0x02, labels=Set(), properties=Map(name -> Eve, age -> 84)))

scala> friendsTable.collect.foreach(println)
20/05/28 22:59:07 ERROR Executor: Exception in task 0.0 in stage 1.0 (TID 3)
java.util.NoSuchElementException: next on empty iterator
	at scala.collection.Iterator$$anon$2.next(Iterator.scala:41)
	at scala.collection.Iterator$$anon$2.next(Iterator.scala:39)
	at scala.collection.IterableLike.head(IterableLike.scala:109)
	at scala.collection.IterableLike.head$(IterableLike.scala:108)
	at scala.collection.AbstractIterable.head(Iterable.scala:56)
	at org.opencypher.morpheus.impl.convert.rowToCypherMap.collectRel(rowToCypherMap.scala:97)
	at org.opencypher.morpheus.impl.convert.rowToCypherMap.constructValue(rowToCypherMap.scala:53)
	at org.opencypher.morpheus.impl.convert.rowToCypherMap.$anonfun$apply$1(rowToCypherMap.scala:45)
	at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:238)
	at scala.collection.immutable.Set$Set1.foreach(Set.scala:97)
	at scala.collection.TraversableLike.map(TraversableLike.scala:238)
	at scala.collection.TraversableLike.map$(TraversableLike.scala:231)
	at scala.collection.AbstractSet.scala$collection$SetLike$$super$map(Set.scala:51)
	at scala.collection.SetLike.map(SetLike.scala:104)
	at scala.collection.SetLike.map$(SetLike.scala:104)
	at scala.collection.AbstractSet.map(Set.scala:51)
	at org.opencypher.morpheus.impl.convert.rowToCypherMap.apply(rowToCypherMap.scala:45)
	at org.opencypher.morpheus.impl.convert.rowToCypherMap.apply(rowToCypherMap.scala:40)
	at org.apache.spark.sql.catalyst.expressions.GeneratedClass$GeneratedIteratorForCodegenStage1.mapelements_doConsume_0$(Unknown Source)
	at org.apache.spark.sql.catalyst.expressions.GeneratedClass$GeneratedIteratorForCodegenStage1.deserializetoobject_doConsume_0$(Unknown Source)
	at org.apache.spark.sql.catalyst.expressions.GeneratedClass$GeneratedIteratorForCodegenStage1.processNext(Unknown Source)
	at org.apache.spark.sql.execution.BufferedRowIterator.hasNext(BufferedRowIterator.java:43)
	at org.apache.spark.sql.execution.WholeStageCodegenExec$$anon$1.hasNext(WholeStageCodegenExec.scala:726)
	at org.apache.spark.sql.execution.SparkPlan.$anonfun$getByteArrayRdd$1(SparkPlan.scala:321)
	at org.apache.spark.rdd.RDD.$anonfun$mapPartitionsInternal$2(RDD.scala:872)
	at org.apache.spark.rdd.RDD.$anonfun$mapPartitionsInternal$2$adapted(RDD.scala:872)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:52)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:349)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:313)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:90)
	at org.apache.spark.scheduler.Task.run(Task.scala:127)
	at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$3(Executor.scala:441)
	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1377)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:444)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:835)

scala> print(graph)
ScanGraph(NodePattern(NODE(:Person)), RelationshipPattern(RELATIONSHIP(:KNOWS)))

**Comment by purush-git** [comment]
Hello @Mats-SX 

Issue got fixed. Looks like this issue is with Spark version 3.0, It works fine with spark 2.4.2. Probably it needs rebuild with some additional libraries. Appreciate your response.

**Comment by Mats-SX** [comment]
@purush-git Glad to hear that you found the issue. Yes it's correct that we are compatible _only_ with Spark 2.4. Currently we do not plan to upgrade the dependency to Spark 3.0, as development of the project has come to a pause.

Thanks for reaching out to us!

**Comment by MarcianoAvihay** [comment]
Hi , a note regarding spark 3 -  after tinkering with the gradle build.params a little i am able to run on a spark 3 image (both preview-2 and rc-1 ) . seems like all tests pass , and aside for the open issue i opened 2 days ago (which is not spark version related ) seems like all tests pass and morpheus functions correctly.  ping me if you want my build.params ( can also submit a merge request )

**Comment by purush-git** [comment]
Hello @MarcianoAvihay , Thank you so much. Would you be able to push the updated version of Jar in your GitRepo please?
